### ISSUE TITLE
Добавить в список сборку под платформу macOS

### ISSUE THREAD

**Issue by voltangle** [AlexGyver/GyverBrick#3]
Название говорит само за себя)
Надеюсь у тебя получится собрать под macOS, ну или хотя бы дать инструкцию как запустить аппку с другой платформы(например с винды) на macOS

**Comment by GyverLibs** [comment]
Можно исходник открыть в processing, он кроссплатформенный

**Comment by AlexGyver** [comment]
![sht](https://user-images.githubusercontent.com/21090953/134781366-4111782d-8761-49d4-b09a-2188be4be8f7.png)
у меня не даёт экспортировать под макось, возможно это можно сделать только под макосью

**Comment by voltangle** [comment]
Да, это можно сделать только под macOS, ведь тулзы есть только под мак
Могу собрать ес хош)

**Comment by AlexGyver** [comment]
давай

**Comment by voltangle** [comment]
Снова привет
Я в скором времени сделаю сборку под мак, но есть такой вопрос
А как ты использовал либу Quantize? Пытаюсь заюзать в своем проекте, но он плюет массив с одним лишь пикселем
Массив с пикселями который я ему кормлю тот что нужно

**Comment by GyverLibs** [comment]
К этой либе прилагается ещё файлик qimage.pde, он всю магию делает

**Comment by voltangle** [comment]
Да, посмотрел как он работает, допер что функция в Quantize отдает только палитру цветов а не готовое изображение
Я тупо скопировал твой код, адаптировал под стандартный JVM проект(ну и добавив либы Processing), и все завелось

**Comment by voltangle** [comment]
А как ты его собирал? Я пытаюсь его собрать под macOS, но при попытке запустить готовое приложение получаю просто белое окно

**Comment by GyverLibs** [comment]
Ну, в процессинге запуск нажимаешь и всё) не знаю, у эплов мб надо бабла куда нибудь занести, там по другому ничего не делается

**Comment by voltangle** [comment]
Нет, бабло нужно занести что бы подписать приложение, типо не давало предупреждение при запуске, а так собрать может кто угодно

**Comment by GyverLibs** [comment]
Ну, кек)
