### ISSUE TITLE
Bug: не работает сохранение результата

### ISSUE THREAD

**Issue by alfonder** [AlexGyver/GyverBrick#6]
После генерации схемы невозможно сохранить результат в файл. Кнопка "сохранить" ничего не делает.
Проверял на Windows 10 и Ubuntu 21.10. Установлена Oracle Java 8.

**Comment by GyverLibs** [comment]
Результат должен молча появиться в папке с программой. Никаких ошибок не выдает, не зависает?

**Comment by alfonder** [comment]
Да, действительно. Просто никаких признаков сохранения, и я многократными нажатиями затёр удачные варианты. Может, стоит хотя бы сделать всплывающее сообщение "Схема сохранена". Тогда будет понятно, что где-то надо искать файл.

**Comment by GyverLibs** [comment]
Это processing, очень сложно сделать что то всплывающее отдельное))

**Comment by alfonder** [comment]
Тогда лучший выход - написать об этом в readme. Еще здорово было бы не затирать предыдущий файл экспорта (тем более, что к нему вернуться позже невозможно), а например в имя файла добавлять timestamp или рандомный хэш.

**Comment by GyverLibs** [comment]
Да, об этом думал, добавлю

**Comment by AlexGyver** [comment]
Сделал с таймкодом
